In [54]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import tensorflow as tf

In [55]:
with open('15jun26_label_encoder.pkl','rb') as f:
    le=pickle.load(f)

In [56]:
with open('15jun26_one_hot_encoder.pkl','rb') as f:
    onehot=pickle.load(f)

In [57]:
with open('15jun26_Scaler.pkl','rb') as f:
    scaler=pickle.load(f)

In [58]:
model=load_model('15jun26_ANNmodel.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [59]:
user={'Pclass':3,'Sex':'female','SibSp':1,'Parch':1,'Fare':12.25,'Embarked':'Q'}
user

{'Pclass': 3,
 'Sex': 'female',
 'SibSp': 1,
 'Parch': 1,
 'Fare': 12.25,
 'Embarked': 'Q'}

# converting the data into dataframe format

In [60]:
user=pd.DataFrame([user])

In [61]:
user

   Pclass     Sex  SibSp  Parch   Fare Embarked
0       3  female      1      1  12.25        Q

# how to make use of label encoder and one hot encoder to transform the user data

In [62]:
user['Sex']=le.transform(user['Sex']) 
# we will not use fit_tranform- this will be used when we are training the model.
#when we are making prediction we will use transform only. because we have already fitted the label encoder on the training data. so we will use the same label encoder to transform the user data.

In [63]:
embarked=onehot.transform(user[['Embarked']]).toarray()
embarked

array([[0., 1., 0.]])

In [64]:
Embarked=pd.DataFrame(embarked,columns=onehot.get_feature_names_out())
Embarked

   Embarked_C  Embarked_Q  Embarked_S
0         0.0         1.0         0.0

In [65]:
user=pd.concat([user.drop(columns=['Embarked']),Embarked],axis=1)

# Scaling the user data

In [66]:
num_cols=['Pclass','SibSp','Parch','Fare']

In [67]:
user[num_cols]=scaler.transform(user[num_cols])

In [68]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0.824071,0,0.442326,0.8339,-0.168928,0.0,1.0,0.0

# Prediction

In [69]:
y=model.predict(user)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 307ms/step

In [70]:
y

array([[0.18060443]], dtype=float32)

# The out is the probability of the user survived or not. if the value is greater than 
# 0.5 then we can say that the user is survived otherwise not survived.

In [73]:
Y=y[0][0]

In [74]:
if y>0.5 :
    print('The person is likely to survive')
else:
    print('The person is likely to not survive')

The person is likely to not survive