In [109]:
import pandas as pd
import numpy as np

In [110]:
data=pd.read_csv(r'C:\Users\ajayr\Desktop\DL Projects\huge_1M_titanic.csv')

In [111]:
print(data.shape)
print(data.info())

(1000000, 12)
<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  str
 4   Sex          1000000 non-null  str
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  str
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   str
 11  Embarked     997760 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 132.6 MB
None

In [112]:
data.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age            198600
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin          770195
Embarked         2240
dtype: int64

In [113]:
data.drop(columns=["PassengerId","Ticket","Name","Cabin","Age"],inplace=True)

In [114]:
data

        Survived  Pclass     Sex  SibSp  Parch        Fare Embarked
0              1       1  female      0      0   76.760165        C
1              0       3    male      0      0   10.193097        S
2              0       3    male      0      0   12.029416        C
3              0       3    male      0      0   13.429448        S
4              0       3    male      0      0    4.840769        C
...          ...     ...     ...    ...    ...         ...      ...
999995         0       2    male      0      0   26.196512        S
999996         1       1  female      0      0  102.555248        S
999997         0       3    male      1      0    8.274807        S
999998         0       2    male      1      0    0.000000        S
999999         1       1  female      1      0   57.720316        S

[1000000 rows x 7 columns]

In [115]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [116]:
data['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

### Data Cleaning

In [117]:
data.dropna(subset=['Embarked'],inplace=True)

In [118]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

### Data Encdoing 
#### Pcclass - Ordnial Column 
#### Gendar - Label Encoder (When we have two categories - Binary )
#### Embarked - One hot encoder (converted into 3 seperate columns - as they have 3 categoroes (C,S,Q))

In [119]:
data.info()

<class 'pandas.DataFrame'>
Index: 997760 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Survived  997760 non-null  int64
 1   Pclass    997760 non-null  int64
 2   Sex       997760 non-null  str
 3   SibSp     997760 non-null  int64
 4   Parch     997760 non-null  int64
 5   Fare      997760 non-null  float64
 6   Embarked  997760 non-null  str
dtypes: float64(1), int64(4), str(2)
memory usage: 66.6 MB

In [120]:
data['Fare']=data['Fare'].astype('int8')

# Feature encoding - Later we need to convet this into pickle formar

In [121]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [122]:
data['Sex']=le.fit_transform(data['Sex'])

In [123]:
data.head()

   Survived  Pclass  Sex  SibSp  Parch  Fare Embarked
0         1       1    0      0      0    76        C
1         0       3    1      0      0    10        S
2         0       3    1      0      0    12        C
3         0       3    1      0      0    13        S
4         0       3    1      0      0     4        C

In [124]:
from sklearn.preprocessing import OneHotEncoder
onehot=OneHotEncoder()

In [125]:
embarked=onehot.fit_transform(data[['Embarked']]).toarray()

In [126]:
embarked

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], shape=(997760, 3))

In [127]:
Embarked=pd.DataFrame(embarked,columns=onehot.get_feature_names_out())

In [128]:
Embarked.isnull().sum()

Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [129]:
data=pd.concat([data.drop(columns=['Embarked']),Embarked],axis=1)

In [130]:
data.dropna(subset='Survived',inplace=True)
data.dropna(subset='Embarked_C',inplace=True)
data.dropna(subset='Embarked_Q',inplace=True)
data.dropna(subset='Embarked_S',inplace=True)

In [131]:
data.isnull().sum()

Survived      0
Pclass        0
Sex           0
SibSp         0
Parch         0
Fare          0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64

### Data Scaling 
# Not required to apply the scaling for Embarked_ columns and Sex(Gendar colum) which are transformed

In [132]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [133]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare', 'Embarked_C',
       'Embarked_Q', 'Embarked_S'],
      dtype='str')

In [134]:
num_cols=['Pclass','SibSp','Parch','Fare']

In [135]:
data[num_cols]=scaler.fit_transform(data[num_cols])

In [136]:
data.head(5)

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,1.0,-1.568955,0.0,-0.462632,-0.469293,1.675910,1.0,0.0,0.0
1,0.0,0.824071,1.0,-0.462632,-0.469293,-0.234040,0.0,0.0,1.0
2,0.0,0.824071,1.0,-0.462632,-0.469293,-0.176163,1.0,0.0,0.0
3,0.0,0.824071,1.0,-0.462632,-0.469293,-0.147224,0.0,0.0,1.0
4,0.0,0.824071,1.0,-0.462632,-0.469293,-0.407672,1.0,0.0,0.0

### Store the Scaler and tew encoders for future use - Convert them to Pickle format

In [137]:
import pickle

In [138]:
with open('15Jun26_label_encoder.pkl','wb') as file:
    pickle.dump(le,file)

In [139]:
with open('15jun26_One_hot_encoder.pkl','wb') as file:
    pickle.dump(onehot,file)

In [140]:
with open('15jun26_scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

### Train Test Validation Split

In [141]:
X=data.drop(columns=['Survived'])

In [142]:
y=data['Survived']

In [143]:
X.head()

,Pclass,Sex,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,-1.568955,0.0,-0.462632,-0.469293,1.675910,1.0,0.0,0.0
1,0.824071,1.0,-0.462632,-0.469293,-0.234040,0.0,0.0,1.0
2,0.824071,1.0,-0.462632,-0.469293,-0.176163,1.0,0.0,0.0
3,0.824071,1.0,-0.462632,-0.469293,-0.147224,0.0,0.0,1.0
4,0.824071,1.0,-0.462632,-0.469293,-0.407672,1.0,0.0,0.0

In [144]:
y.head()

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Survived, dtype: float64

In [145]:
from sklearn.model_selection import train_test_split

In [146]:
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# for validation taking the 20% from the training data

In [147]:
x_train,x_valid,y_train,y_valid=train_test_split(X_train,Y_train,test_size=0.2,random_state=42)

In [148]:
print(x_train.shape,x_valid.shape,y_train.shape,y_valid.shape)

(637136, 8) (159284, 8) (637136,) (159284,)

# Model Building

In [149]:
import tensorflow as tf

In [150]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense 
from tensorflow.keras.callbacks import EarlyStopping

In [151]:
x_train.shape[1]

8

In [152]:
model=Sequential([Dense(64,input_shape=(x_train.shape[1],),activation='relu'), # first hidden Layer 
Dense(32,activation='relu'), # second hidden layer
Dense(1,activation='sigmoid')]) # output layer
# 64 ,32,1 are no of nodes in each layer. 1 is output layer as we have binary classification problem.
# we are using relu activation function as tanh and sigmoid can cause vanishing gradient problem.
# we are using sigmoid activation function in output layer as it gives output between 0 and 1 which is suitable for binary classification problem.

c:\Users\ajayr\Desktop\DL Projects\venvdl\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [153]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

In [154]:
# 576 = input nodes 8 and 64 hidden layer = 8*64+64 = 576
# 2080 = 64 * 32 + 32 =

In [155]:
# using the hyperparameter tuning where in you will decide how many no of node ,hidden layer we 
# can go for it

In [156]:
## With respect model combilation what optimizer and loss fucntion we can go for it

In [157]:
opt=tf.keras.optimizers.Adam(learning_rate=0.001)
# loss=tensorflow.keras.losses.BinaryCrossentropy(from_logits=False)
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [158]:
stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [159]:
model.fit(X_train,Y_train,validation_data=(x_valid,y_valid),epochs=10,callbacks=[stopping_callback])

Epoch 1/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 65s 2ms/step - accuracy: 0.8413 - loss: 0.3535 - val_accuracy: 0.8241 - val_loss: 0.3533
Epoch 2/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 63s 3ms/step - accuracy: 0.8515 - loss: 0.3351 - val_accuracy: 0.8521 - val_loss: 0.3333
Epoch 3/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 59s 2ms/step - accuracy: 0.8532 - loss: 0.3309 - val_accuracy: 0.8536 - val_loss: 0.3291
Epoch 4/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 58s 2ms/step - accuracy: 0.8539 - loss: 0.3290 - val_accuracy: 0.8539 - val_loss: 0.3288
Epoch 5/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 61s 2ms/step - accuracy: 0.8543 - loss: 0.3278 - val_accuracy: 0.8526 - val_loss: 0.3291
Epoch 6/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 59s 2ms/step - accuracy: 0.8547 - loss: 0.3271 - val_accuracy: 0.8532 - val_loss: 0.3267
Epoch 7/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 62s 2ms/step - accuracy: 0.8551 - loss: 0.3266 - val_accuracy: 0.8557 - val_loss: 0.3245
Epoch 8/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 61s 2ms/step - accuracy: 0.8552 - loss: 0.3262 - val_accuracy: 0.8555 - val_loss: 0.3257
Epoch 9/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 59s 2ms/step - accuracy: 0.8552 - loss: 0.3259 - val_accuracy: 0.8550 - val_loss: 0.3268
Epoch 10/10
24889/24889 ━━━━━━━━━━━━━━━━━━━━ 61s 2ms/step - accuracy: 0.8553 - loss: 0.3257 - val_accuracy: 0.8560 - val_loss: 0.3244

In [162]:
model.save('15jun26_ANNmodel.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [161]:
x_train.isnull().sum()

Pclass        0
Sex           0
SibSp         0
Parch         0
Fare          0
Embarked_C    0
Embarked_Q    0
Embarked_S    0
dtype: int64